version: '1.0.3'
history:
  '1.0.3':
    date: '2020-07-16'
    title: 'Readme buto_folder'
    description: 'Add readme file to buto_data folder.'
  '1.0.2':
    date: '2020-07-16'
    title: 'Public folder'
    description: 'Add public folder.'
  '1.0.1':
    date: '2020-07-16'
    title: 'buto_data files'
    description: 'Add buto_data files.'
  '1.0.0':
    date: '2020-07-16'
    title: 'First version'
    description: 'Add files.'
