version: '1.4.0'
history:
  '1.4.0':
    date: '2020-09-30'
    title: 'Improvement'
    description: 'More improvements.'
  '1.3.0':
    date: '2020-09-29'
    title: 'Improvement'
    description: 'Improvement to make this work without copy content from buto_data folder. This should improve the start up process.'
  '1.2.0':
    date: '2020-09-29'
    title: 'Content'
    description: 'Check for content from existing files.'
  '1.1.1':
    date: '2020-08-31'
    title: 'Modals size'
    description: 'Sign in and Create account modals made smaller.'
  '1.1.0':
    date: '2020-08-26'
    title: 'Modal sign in'
    description: 'Add js file and open sign in with a modal window.'
  '1.0.6':
    date: '2020-08-06'
    title: 'Template files'
    description: 'Improved tempate files client.yml and unknown.yml.'
  '1.0.5':
    date: '2020-08-06'
    title: 'Mysql path'
    description: 'Change mysql file path form plugin account/admin_v1.'
  '1.0.4':
    date: '2020-07-16'
    title: 'Readme public'
    description: 'Add readme file to public folder.'
  '1.0.3':
    date: '2020-07-16'
    title: 'Readme buto_folder'
    description: 'Add readme file to buto_data folder.'
  '1.0.2':
    date: '2020-07-16'
    title: 'Public folder'
    description: 'Add public folder.'
  '1.0.1':
    date: '2020-07-16'
    title: 'buto_data files'
    description: 'Add buto_data files.'
  '1.0.0':
    date: '2020-07-16'
    title: 'First version'
    description: 'Add files.'
