plugin_modules:
  p:
    plugin: 'wf/doc'
  account:
    plugin: 'wf/account2'
    settings: null
  accountadmin:
    plugin: 'account/admin_v1'
    settings:
      mysql: 'yml:/../buto_data/theme/dev/theme/mysql.yml'
default_class: p
default_method: home
plugin:
  theme:
    include:
      enabled: true
events:
  load_theme_config_settings_after:
    -
      plugin: 'wf/account2'
      method: signin
