plugin_modules:
  p:
    plugin: 'wf/doc'
  account:
    plugin: 'wf/account2'
    settings:
      allow:
        signin: true
        signin_method: username
        registration: true
        change_email: true
        change_username: true
        change_password: true
        two_factor_authentication: false
        remember: true
        remember_signout_username: true
      two_factor_authentication:
        key_timeout: 600
      mysql: yml:/theme/[theme]/buto_data/mysql.yml
      phpmailer: yml:/theme/[theme]/buto_data/phpmailer.yml
  accountadmin:
    plugin: 'account/admin_v1'
    settings:
      mysql: yml:/theme/[theme]/buto_data/mysql.yml
default_class: p
default_method: home
plugin:
  theme:
    include:
      enabled: true
  yml:
    render:
      enabled: true
  file:
    exist:
      enabled: true
events:
  load_theme_config_settings_after:
    -
      plugin: 'wf/account2'
      method: signin
